config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'main#index'

  resources :posts
  resources :news

  get 'graph', to: 'posts#graph'

  get '/month/:year/:month', to: 'posts#index', as: :month
  get '/week/:year/:week', to: 'posts#index', as: :week
  get '/years/:year', to: 'posts#years', as: :years
  get '/months/:year', to: 'posts#months', as: :months
  get '/weeks/:year', to: 'posts#weeks', as: :weeks
end

app/views/shared/_flash_messages.html.slim
- flash.each do |type, message|
  .col-sm-offset-7.col-sm-3.alert-over.text-center
    div[class="alert #{alert_class_for(type)} alert-dismissible fade in"]
      button.close data-dismiss="alert"
        span aria-hidden="true" &times;
        span class="sr-only" Close
      = message

app/views/shared/_metrics.html.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter27690198 = new Ya.Metrika({id:27690198,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });
    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";
    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/27690198" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<script type="text/javascript">
  var _urq = _urq || [];
  _urq.push(['initSite', 'df6d5ca8-2d6f-4089-bdb9-3c0c71354bfc']);
  (function() {
  var ur = document.createElement('script'); ur.type = 'text/javascript'; ur.async = true;
  ur.src = ('https:' == document.location.protocol ? 'https://cdn.userreport.com/userreport.js' : 'http://cdn.userreport.com/userreport.js');
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ur, s);
  })();
</script>

app/views/shared/_nav.html.slim
nav.navbar.navbar-inverse role='navigation'
  .container
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle data-target='#bs-example-navbar-collapse-1' data-toggle='collapse' type='button'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Viserys', root_path, class: 'navbar-brand'
    /! Collect the nav links, forms, and other content for toggling
    .collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if current_user
          li.btn-group.dropdown
            li= link_to 'Дневник', posts_path
            li
              a.dropdown-toggle(data-toggle='dropdown')
                span.caret
                span.sr-only
              ul.dropdown-menu(role='menu')
                li= link_to 'Недели', weeks_path(Date.today.year)
                li= link_to 'Месяцы', months_path(Date.today.year)
                li= link_to 'Годы', years_path(Date.today.year)
          li
            a.dropdown-toggle(data-toggle='dropdown')
              = current_user.name
            ul.dropdown-menu(role='menu')
              li= link_to 'Настройки', edit_user_registration_path
              li= link_to 'Выход', destroy_user_session_path, data: {method: :delete}

        - else
          li= link_to 'Вход', new_user_session_path
          li= link_to 'Регистрация', new_user_registration_path