config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'main#index'

  resources :posts
  resources :news

  get 'graph', to: 'posts#graph'

  get '/month/:year/:month', to: 'posts#index', as: :month
  get '/week/:year/:week', to: 'posts#index', as: :week
  get '/years/:year', to: 'posts#years', as: :years
  get '/months/:year', to: 'posts#months', as: :months
  get '/weeks/:year', to: 'posts#weeks', as: :weeks
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  before_action :check_user, except: :show

  def index
    @news = News.all
  end

  def show
  end

  def new
    @news = News.new
  end

  def edit
  end

  def create
    @news = News.new(news_params)

    if @news.save
      redirect_to @news, notice: 'News post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @news.update(news_params)
      redirect_to @news, notice: 'News post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @news.destroy
    redirect_to news_index_url, notice: 'News post was successfully destroyed.'
  end

  private

  def set_news
    @news = News.find(params[:id])
  end

  def news_params
    params.require(:news).permit(:title, :content)
  end

  def check_user
    unless current_user && current_user.role == 'admin'
      redirect_to root_path, notice: 'Доступ закрыт :)'
    end
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.slim
= simple_form_for(@news) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :content

  .form-actions
    = f.button :submit, 'Сохранить новость', class: 'btn btn-default'

app/views/news/_news.html.slim
.panel.post
  h4= link_to post.title, post
  - if can? :manage, post
    small=> link_to '[Удалить]', post, method: :delete, data: { confirm: 'Удалить новость?' }
    small=> link_to '[Редактировать]', edit_news_path(post)
  .date= nice_russian_date(post.created_at)
  .content= markdown post.content

app/views/news/edit.html.slim
h1 Редактируем новость

= render 'form'

app/views/news/index.html.slim
h3 Новости
- @news.each do |post|
  = render 'news', post: post
    td = news.title

= link_to 'Добавить новость', new_news_path

app/views/news/new.html.slim
h1 New news

== render 'form'

= link_to 'Back', news_index_path

app/views/news/show.html.slim
= render 'news/news', post: @news